### PR TITLE
updated documentation on call

### PR DESCRIPTION
**Pull request by andrewbaxter439**

### CODE REVIEW

**Comment by andrewbaxter439** [comment]
To resolve #1 
- Adding explanations to parameters passed to `parallel` call of `SimPathsMultiRun`
- removed `seq` and passed to end of `parallel`

**Comment by vkhodygo** [comment]
I'm afraid you'll have to redo this based on the most recent changes.

A few general notes: 

- local variables _should_ use upper case
- do _**not**_ keep documentation in comments, no one is going to read them, they'll be asking you anyway
- general commentaries for fellow developers are acceptable

**Comment by vkhodygo** [comment]
Note that I've changed the repo name.

**Comment by andrewbaxter439** [comment]
Moved to new branch and will pr

**Pull request closed without merging**
